openapi: '3.0.2'
info:
  title: Wildzone suppliers API
  version: '1.0'
servers:
  - url: localhost:8081/api


paths:
  /suppliers/{id}:
    get:
      summary: Get Supplier
      description: Gets a supplier by supplied ID in the URL.
      parameters:
            - in: path
              name: id
              schema:
                type: integer
                minimum: 1
              required: true
              description: Numeric ID of the supplier to get
      responses:
        '200':
          description: Get success
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Supplier'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
    put:
      summary: Update Supplier
      description: Updates a supplier by supplier ID in the URL.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
          minimum: 1
        required: true
        description: Numeric ID of the supplier to get
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Supplier'
      responses:
        '200':
          description: Update success.
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
    delete:
      summary: Delete supplier
      description: Delete supplier by supplied ID in the URL
      parameters:
      - in: path
        name: id
        schema:
          type: integer
          minimum: 1
        required: true
        description: Numeric ID of the supplier to get
      responses:
        '200':
          description: Delete successful
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
                    
  /suppliers:
    get:
      summary: Get suppliers list.
      description: Get all the suppliers in a list.
      responses:
        '200':
          description: Succesfull retrieved JSON array of Suppliers
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Suppliers'

        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
    post:
      summary: Create supplier
      description: Creates a supplier with the parameters specified in the request body.
      requestBody:
        description: This is the supplier object.
        required: true
        content:
          application/json:
            schema: 
              type: object
              $ref: '#/components/schemas/Supplier'

          
      responses:
        '201':
          description: Create a supplier
          content: 
            application/json:     
              schema:
                $ref: '#/components/schemas/Supplier'
                type: object

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
    delete:
      summary: Delete all suppliers
      description: Deletes alle the suppliers in the database.
      responses:
        '200':
          description: Delete successful
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string

components:
  schemas:
    Suppliers:
      description: Array of supplier information
      type: array
      items:
        $ref: '#/components/schemas/Supplier'
    Supplier:
      description: Model containing supplier information
      title: Supplier
      required:
      - name
      - email
      - phoneNumber
      - country
      - place
      - postalCode
      - houseNumber
      - KVKnumber
      type: object
      properties:
        id:
          type: integer
          example: 1

        name:
          type: string
          example: Moses Dunlap

        email:
          type: string
          example: panulyqi@mailinator.com

        phoneNumber:
          type: string
          example: +1 (351) 308-7432

        country:
          type: string
          example: Netherlands

        place:
          type: string
          example: Eindhoven

        postalCode:
          type: string
          example: 1234AB

        houseNumber:
          type: string
          example: 795

        KVKnumber:
          type: integer
          example: 234

        createdAt:
          type: string
          example: 2021-11-17T13:13:56.000Z

        updatedAt:
          type: string
          example: 2021-11-17T13:13:56.000Z

